version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: abema-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: abema_discovery
      MYSQL_USER: abema
      MYSQL_PASSWORD: abema123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
